### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by bvssvni** [comment]
Nice!

**Comment by bvssvni** [comment]
@kvark I think you need to set up permissions properly for this repository. I can't merge.

**Comment by kvark** [comment]
Uh? weird

**Comment by kvark** [comment]
I've added the Developers team, that should fix it.

**Comment by kvark** [comment]
Argh! I forgot to push the latest changes :( Examples will remain blocked: https://github.com/gfx-rs/gfx_examples/pull/15

**Pull request merged**
